title: Christian Sanabria Site
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Christian Sanabria # add your name
author-img: christian-sanabria.jpg # add your photo
about-author: I am a web and software developer focusing on front-end development, back-end development and software development with languages ​​such as c ++, java and python. Always hungry to keep learning. # add description
social-twitter: Christian93san # add your Twitter handle
social-facebook: Christian7sr # add your Facebook handle
social-github: Christian7sr # add your Github handle
social-linkedin: christian-sanabria-rodriguez # add your Linkedin handle
social-email: cdsanabriar@unal.edu.co # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
